on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/**
      - "*.sh"

env:
  # version: m88
  skia_branch: main
  skia_commit: dbfd72770bdd2e7b82d493df8cdda6338fdf7f7c
  release: dbfd72770bdd2e7b82d493df8cdda6338fdf7f7c-1
  archive: true

jobs:

  macos:
    runs-on: macos-15
    strategy:
      matrix:
        arch: ["x86_64", "arm64"]
        build_type: [Release]
      fail-fast: false
    env:
      platform: macos
      build_type: ${{ matrix.build_type }}
      arch: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - run: ./check_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./build_macos.sh
      - uses: actions/upload-artifact@v4
        with:
          name: Skia-${{ env.release }}-macos-${{ matrix.build_type }}-${{ matrix.arch }}.zip
          path: '*.zip'
      - run: ./release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type: [Release]
        arch: ["x86_64", "arm64"]
      fail-fast: false
    env:
      platform: linux
      build_type: ${{ matrix.build_type }}
      arch: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - run: sudo ./prepare_linux.sh
      # - run: ./check_release.sh
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./build_linux.sh
      - uses: actions/upload-artifact@v4
        with:
          name: Skia-${{ env.release }}-linux-${{ matrix.build_type }}-${{ matrix.arch }}.zip
          path: '*.zip'
      - run: ./release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        build_type: [Release]
      fail-fast: false
    env:
      platform: windows
      build_type: ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v2
      # - shell: bash
      #   run: ./check_release.sh
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: microsoft/setup-msbuild@v1.1
      - uses: ilammy/msvc-dev-cmd@v1
      - shell: bash
        run: ./build_windows.sh
      - uses: actions/upload-artifact@v4
        with:
          name: Skia-${{ env.release }}-windows-${{ matrix.build_type }}-x86_64.zip
          path: '*.zip'
      - shell: bash
        run: ./release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
